port: 3000
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: beta
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: true
chdir: /var/www/beta_super_generic_website/current
socket: /tmp/thin.sock
tag: beta_super_generic_website