port: 3001
timeout: 30
wait: 30
pid: tmp/pids/thin.pid
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: true
chdir: /var/www/production_super_generic_website/current
tag: production_super_generic_website