port: 3001
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 1
threaded: true
daemonize: true
chdir: /var/www/production_super_generic_website
tag: production-super-generic-website